### ISSUE TITLE
如何使用hooks中的方法？

### ISSUE THREAD

**Issue by Ncrybo** [yanzhandong/v3hooks#8]
博主您好，您封装的一些hook， 我看了一下，有些只返回了变量， 那么如何使用其中定义好的方法呢？ 是这样：“usexxx.function”的形式使用吗？ 如果这样使用了，那么，其中操作的变量还是我原来hook中返回的变量吗？？

**Comment by yanzhandong** [comment]
可以看一下使用文档，有部分hook他是提供了方法被导出了的 
例: const [ useBooleanState,{ toggle: useBooleanToggle, setTrue, setFalse}] = useBoolean(); 
未提供导出的方法不能直接使用的
